### ISSUE TITLE
Alt clicking while not encumbered is increasing the amount of items in the stack until at encumbrance limit.

### ISSUE THREAD

**Issue by FeedingWolves** [DeekyJay/ValheimMod-DropJustEnough#1]
As title states. Tested as only mod active.

![image](https://user-images.githubusercontent.com/20764889/110243599-018d9080-7f53-11eb-97a7-294c831ce732.png)

**Comment by DeekyJay** [comment]
@FeedingWolves Silly mistake on my part. I noticed this this morning as well. I've updated it to fix this issue!

https://valheim.thunderstore.io/package/DeekyJay/DropJustEnough/1.0.1/
